# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-regions

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage,'prod'}
  region: us-east-2
  lambdaHashingVersion: 20201221
  environment:
    LOGGER_LEVEL: "DEBUG" # CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
    AWS_REGIONS_JSON_URL: "https://raw.githubusercontent.com/jsonmaur/aws-regions/master/regions.json"

custom:
  stages:
    - local
    - prod

functions:
  # health
  health-check:
    handler: health.check
    events:
      - http: GET /health/check
  # get-all-data
  region:
    handler: aws-regions.get_region_info
    events:
      - http:
          path: /region/{region_code}/info
          method: get
          cors: true

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-python-requirements
  - serverless-offline
